-- Usuários (identidade). DDL portável (H2 + PostgreSQL).
CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    document  VARCHAR(14)  NOT NULL UNIQUE,
    email     VARCHAR(255) NOT NULL UNIQUE,
    password  VARCHAR(72)  NOT NULL,
    type      VARCHAR(20)  NOT NULL
);
