-- Carteiras (saldo). DDL portável (H2 + PostgreSQL).
-- 'version' suporta o lock otimista (@Version). 1:1 com usuário via user_id único.
CREATE TABLE wallets
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT         NOT NULL UNIQUE,
    balance NUMERIC(19, 2) NOT NULL,
    version BIGINT         NOT NULL
);
