-- Transferências concluídas + chave de idempotência. DDL portável (H2 + PostgreSQL).
-- idempotency_key é UNIQUE (NULLs múltiplos permitidos) para impedir débito duplicado.
CREATE TABLE transfers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payer_id        BIGINT                   NOT NULL,
    payee_id        BIGINT                   NOT NULL,
    amount          NUMERIC(19, 2)           NOT NULL,
    idempotency_key VARCHAR(100) UNIQUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
